apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: expense-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: expense-app
  template:
    metadata:
      labels:
        app: expense-app
    spec:
      containers:
      - name: expense-app-container
        image: uk.icr.io/expense-app-ns/expense-app-repo@sha256:e936c3b7119367579a2a85f264404124f00f0b562cb67d11253626811764f10e
        ports:
        - containerPort: 5000